site_name: LiquidAmber Docs
site_url: https://www.liquidamber.ai/help/
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
nav:
  - Home: index.md
  - Products:
      - Discover:
          - Overview: discover.md
          - Getting Started: discover-getting-started.md
          - User Interface Guide: discover-interface.md
          - Research Trails & Response Tools: discover-research-trails.md
          - Discover Local Two-Step Journalist Guide: discover-local-two-step-journalist-guide.md
          - Administration:
            - Overview: admin.md
            - Users: admin-users.md
            - Organizations & Outlets: admin-outlets.md
            - Announcements: admin-announcements.md
            - Feedback: admin-feedback.md
      - Engage: engage.md
      - Verify: verify.md
      - Describe: describe.md
  - About: about.md
  - Contact: contact.md
